[build]
  command = "npm install && npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Performance headers
[[headers]]
  for = "*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "*.css"
  [headers.values]
    Content-Type = "text/css"

[[headers]]
  for = "*.gltf"
  [headers.values]
    Content-Type = "model/gltf+json"

[[headers]]
  for = "*.glb"
  [headers.values]
    Content-Type = "model/gltf-binary"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"

# Build environment
[build.environment]
  NODE_ENV = "production"
  NODE_VERSION = "20.11.0"
  NPM_USE_PRODUCTION = "false"